version: '3.7'
services:
  api:
    container_name: 'feature-toggle-api'
    build: './cmd'
    ports:
      - '8080:8080'
    depends_on:
      - 'mongo'
  mongo:
    image: 'mongo:latest'
    container_name: 'mongo'
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: admin
    ports:
      - '27017:27017'
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mmongo-init.js:ro
      - ./mongo-volume:/data/db
volumes:
  mongodata: